services:
  jupyter-lab:
    image: fazeeia/dsci522-dockerfile-bank
    ports:
    - "8888:8888"
    volumes:
    - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
