name: bankenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - matplotlib=3.9.2
  - numpy=1.26.0
  - pandas=2.2.2
  - scikit-learn=1.3.2
  - seaborn=0.13.2
  - altair=5.1.0
  - pip=24.0
  - pandera=0.9.0
  - scipy=1.11.2
  - ipython=8.12.0  
  - pip:
    - altair-ally 
