name: bankenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # I recommend Python 3.10 for better compatibility
  - matplotlib=3.9.2
  - numpy=1.23.5  # Compatible with scikit-learn and scipy
  - pandas=1.5.3  # Stable version of pandas
  - scikit-learn=1.2.2  # Compatible with numpy 1.23.x
  - seaborn=0.13.2
  - altair=5.1.0
  - pip=24.0
  - scipy=1.10.1  # Compatible with numpy 1.23.x
  - ipython=8.12.0
  - nbformat=5.9.2
  - jupyter=1.0.0
  - jupyterlab=4.0.5
  - quarto=1.3.433
  - pip:
      - altair-ally==0.1.1
      - pandera==0.8.1
      - tabulate 
